### ISSUE TITLE
No output file anymore

### ISSUE THREAD

**Issue by 1GR3** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#73]
I've been occasionally using this plugin with more or less success on MacOS 10-14-5 nit since I had scaling issues again, I decided to update both Inkscape to v1.1.2 and the Laser Tool to v2.4 but now All I get is this message:
`Traceback (most recent call last):
  File "laser.py", line 290, in <module>
    effect.run()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "laser.py", line 63, in effect
    if os.path.isfile(self.options.header_path):
  File "/Applications/Inkscape.app/Contents/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/../../../../lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
`

**Comment by 1GR3** [comment]
I've found the old v1.1 in the downloads folder and now it works again and I have the scaling and positioning issues again.
